<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aggregator.Aggregation.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Aggregator.Common.Application\Aggregator.Common.Application.csproj" />
  </ItemGroup>

</Project>
